name: Terraform Apply

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-apply:
    name: Manual Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::145185392705:role/GitHubActionsTerraformMediaServicesRole
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.13.1

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform validate
        run: terraform validate

      - name: Terraform apply
        run: |
          terraform apply -auto-approve -input=false \
            -var="aws_region=us-east-1" \
            -var="flow_name=tf-mc-srt-listener-flow" \
            -var="srt_port=5000"

      - name: Show Terraform outputs
        run: terraform output