name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-check:
    name: Terraform Format Validate Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::xxxxxxxxxxxx:role/GitHubActionsTerraformMediaServicesRole
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.13.1

      - name: Terraform format check
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: |
          terraform plan -input=false \
            -var="aws_region=${{ vars.AWS_REGION }}" \
            -var="flow_name=${{ vars.FLOW_NAME }}" \
            -var="srt_port=${{ vars.SRT_PORT }}"
